NRM-261 Add “Do you have information about where the exploiters are?”…
UKHomeOffice/modern-slavery pull request #614
Opened 2024-05-23 12:09 UTC by PaolaDMadd-Pro

##What?
add new pages for exploiters location details with tests

## Why?
As requested by product owner per ticket [NRM 261](https://collaboration.homeoffice.gov.uk/jira/browse/NRM-261)

## How?
- add relevant views, validations, fields
- update submission and summary report files to include the new changes.
- add ui-Integration and acceptance tests for new pages
- update .snyk vulnerabilities file
- increased default timeout from 5 to 20min for acceptance test
- update puppeteer

## Testing?
unit test and integration test pass
acceptance tests: additional tests made exceeded timeout limit increased it to 20min.

## Screenshots (optional)
## Anything Else? (optional)

## Check list
- [ ] I have reviewed my own pull request for linting issues (e.g. adding new lines)
- [ ] I have written tests (if relevant)
- [ ] I have created a JIRA number for my branch
- [ ] I have created a JIRA number for my commit
- [ ] Ensure drone builds are green especially tests
- [ ] I will squash the commits before merging

2024-05-23 15:15 UTC, Rhodine-orleans-lindsay requested changes
A few suggestions and some syntax issues to correct

2024-05-23 15:15 UTC, Rhodine-orleans-lindsay commented on test/_ui-integration/nrm/validations.spec.js
> +
remove extra line

2024-05-23 15:15 UTC, Rhodine-orleans-lindsay commented on test/_ui-integration/nrm/automatic-referral-application.spec.js
> +
remove extra line

2024-05-23 15:15 UTC, Rhodine-orleans-lindsay commented on test/_ui-integration/nrm/application.spec.js
> +
remove extra line

2024-05-23 15:15 UTC, Rhodine-orleans-lindsay commented on test/_ui-integration/nrm/application.spec.js
> +  });
add a new line after

2024-05-23 15:15 UTC, Rhodine-orleans-lindsay commented on apps/nrm/views/where-are-exploiters.html
> +{{/partials-page}}
needs a new line after

2024-05-23 15:15 UTC, Rhodine-orleans-lindsay commented on apps/nrm/views/information-exploiters-location.html
> +{{/partials-page}}
needs a  new line after

2024-05-23 15:15 UTC, Rhodine-orleans-lindsay commented on apps/nrm/views/information-exploiters-location.html
> +
remove extra lines

2024-05-23 15:15 UTC, Rhodine-orleans-lindsay commented on apps/nrm/views/exploiters-uk.html
> +{{/partials-page}}
needs a new line after

2024-05-23 15:15 UTC, Rhodine-orleans-lindsay commented on apps/nrm/translations/src/en/pages.json
> +
remove extra line

2024-05-23 15:15 UTC, Rhodine-orleans-lindsay commented on apps/nrm/translations/src/en/fields.json
> +
remove extra line

2024-05-23 15:15 UTC, Rhodine-orleans-lindsay commented on apps/nrm/translations/src/en/fields.json
> +
remove extra line

2024-05-23 15:15 UTC, Rhodine-orleans-lindsay commented on apps/nrm/translations/src/en/fields.json
> +
remove extra line

2024-05-23 15:15 UTC, Rhodine-orleans-lindsay commented on apps/nrm/translations/src/en/fields.json
> +
remove extra line

2024-05-23 15:15 UTC, Rhodine-orleans-lindsay commented on apps/nrm/index.js
> +    '/where-are-exploiters': {
I'd make the step name the same as the field name (exploiters-current-location-details), it fits the question more

2024-05-23 15:15 UTC, Rhodine-orleans-lindsay commented on apps/nrm/index.js
> +    '/information-exploiters-location': {
I'd make the step name the same as the field name (exploiters-location)

2024-05-23 16:03 UTC, Rhodine-orleans-lindsay commented on test/_ui-integration/nrm/validations.spec.js
> +
there is still an extra line there

2024-05-23 16:03 UTC, Rhodine-orleans-lindsay commented on test/_ui-integration/nrm/automatic-referral-application.spec.js
> +
there's still an extra line there

2024-05-23 16:04 UTC, Rhodine-orleans-lindsay commented on test/_ui-integration/nrm/application.spec.js
> +
there is still an extra line

2024-05-23 16:29 UTC, Rhodine-orleans-lindsay commented on apps/nrm/translations/src/en/fields.json
> +  "exploiters-location" : {
format colon spaces

2024-05-23 16:30 UTC, Rhodine-orleans-lindsay commented on apps/nrm/translations/src/en/fields.json
> +  "are-exploiters-in-the-uk" : {
format colon spaces

2024-05-29 11:48 UTC, PaolaDMadd-Pro commented on test/_ui-integration/nrm/validations.spec.js
> +
path name changed.

2024-05-29 14:37 UTC, Rhodine-orleans-lindsay approved these changes
lgtm

2024-06-10 14:01 UTC, sulthan-ahmed approved these changes
for some reason the hint is being captured with the visually-hidden so @PaolaDMadd-Pro explained that they are providing a workaround.  As @Rhodine-orleans-lindsay is working on updating HOF, this will fix this workaround later so will approve this

2024-09-12 13:12 UTC, closed without merging