[NRM 330] added paragraph text in the legend for py-under-age field
UKHomeOffice/modern-slavery pull request #687
Opened 2024-11-14 15:48 UTC by Adesh-Ramchurn

## What?
## Why?
## How?
## Testing?
## Screenshots (optional)
## Anything Else? (optional)
## Check list

- [ ] I have reviewed my own pull request for linting issues (e.g. adding new lines)
- [ ] I have written tests (if relevant)
- [ ] I have created a JIRA number for my branch
- [ ] I have created a JIRA number for my commit
- [ ] I have followed the chris beams method for my commit https://cbea.ms/git-commit/
here is an [example commit](https://github.com/UKHomeOfficeForms/hof/commit/810959f391187c7c4af6db262bcd143b50093a6e)
- [ ] Ensure drone builds are green especially tests
- [ ] I will squash the commits before merging

2024-11-18 18:28 UTC, tobyschaefferHO requested changes
Update works great - wouldn't have thought of that.  William and Rhodine have expressed they want us to place text within the pages.json file, and to use those entries within our html templates - would you mind doing that?  Once you've got that i'll be happy to approve.  thanks again - nice work!

2024-11-18 18:28 UTC, tobyschaefferHO commented on apps/nrm/views/pv-under-age.html
> +    <p>If they’re under 18 or you’re not sure, you must explain to them how organisations such as the Home Office will use their information.</p>
would you replace these with entries places in the route under pages.json?  It'll be more consistent with our use of the translation library.

2024-11-18 18:28 UTC, tobyschaefferHO commented on apps/nrm/views/pv-under-age.html
> +  <div  tabindex="0">
extra space here should be deleted.  
```suggestion
  <div tabindex="0">
```

2024-11-21 09:07 UTC, william-gu-hof approved these changes

2024-12-05 09:19 UTC, tobyschaefferHO approved these changes
code looks good 👍

2024-12-05 09:20 UTC, tobyschaefferHO commented
Merging as branch test approval received.

2024-12-05 09:20 UTC, merged